### ISSUE TITLE
OpenCV params definitions url is out of date

### ISSUE THREAD

**Issue by hop-soellingeraj** [colmap/privacy_preserving_sfm#1]
https://github.com/colmap/privacy_preserving_sfm/blob/7b60fbc625af9fd9c8fb8f669497d4342eb20d07/src/base/camera_models.h#L262

**Comment by mgprt** [comment]
I get redirected, but in principle it seems to work.
Or is there any issue with the referenced page?

**Comment by free-soellingeraj** [comment]
Oh right nevermind.
Must've just been on my side.
We can close this.
